<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_newnamepre1</name>
   <tag></tag>
   <elementGuidId>8295b251-411f-4d86-9377-9b27cdc20c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='enhanced-table-checkbox-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#enhanced-table-checkbox-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>11e08987-226b-48a4-b817-4766450e99ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone MuiTableCell-sizeMedium css-1361h17</value>
      <webElementGuid>42255a30-6757-44b8-bcb7-485685d2c175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>d7b3731d-b614-4a90-9893-f9c2c52abfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enhanced-table-checkbox-0</value>
      <webElementGuid>c888e56f-c2f2-4447-a9b2-b502c54a1926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newnamepre1</value>
      <webElementGuid>e7b16bb4-298f-4379-b66f-6f359f75dfbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enhanced-table-checkbox-0&quot;)</value>
      <webElementGuid>d1ccb9ee-0a8c-447c-86b1-617d2cc445d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='enhanced-table-checkbox-0']</value>
      <webElementGuid>17f67a76-7fa8-4098-864e-0f9766113e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div[2]/table/tbody/tr/th</value>
      <webElementGuid>d19eb47c-e635-4948-9e5a-c57920b43f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[1]/following::th[1]</value>
      <webElementGuid>958314a4-7189-4a55-8960-c0a83fcb7d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::th[2]</value>
      <webElementGuid>c38dcbc5-2cb6-42b1-9f1b-8c19bbc4d22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account1'])[2]/preceding::th[1]</value>
      <webElementGuid>b7381e16-268c-4202-a246-75edf96a5fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testgroup1'])[2]/preceding::th[1]</value>
      <webElementGuid>71af3b2b-33c1-4564-824d-3e2e16623fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='newnamepre1']/parent::*</value>
      <webElementGuid>9fa56cd8-dab0-48e2-9c41-6f29e0e06533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>1f4dbcf5-be0a-41a4-9c70-cad9836ce1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'enhanced-table-checkbox-0' and (text() = 'newnamepre1' or . = 'newnamepre1')]</value>
      <webElementGuid>30c29884-2587-4056-873a-6688f9bf6a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
