<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_testgroup2</name>
   <tag></tag>
   <elementGuidId>24a9b5c4-2b86-4bae-9bf9-663af7159fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[3]/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.MuiTypography-root.MuiTypography-h5.css-72ogzh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>33b60863-71b0-404b-bfcb-77abde7005e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 css-72ogzh</value>
      <webElementGuid>be4ff4c6-4be9-450a-bfdb-8edde4e9dae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testgroup2</value>
      <webElementGuid>eb1722f7-cb42-406f-947f-2409573839e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiStack-root css-48h5p0&quot;]/div[@class=&quot;MuiBox-root css-kzfr2u&quot;]/div[@class=&quot;MuiStack-root css-1xctuv5&quot;]/div[@class=&quot;MuiStack-root css-1uoxajw&quot;]/h5[@class=&quot;MuiTypography-root MuiTypography-h5 css-72ogzh&quot;]</value>
      <webElementGuid>eaf1b8bc-4092-4241-8a91-47956bc88136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/div/div/h5</value>
      <webElementGuid>d914ce86-03a2-40c5-a093-12a3dd60f867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[1]/following::h5[1]</value>
      <webElementGuid>f6333318-4578-471b-b723-88926d369593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::h5[1]</value>
      <webElementGuid>d2e86372-0a13-4bd2-95b2-bc736e555fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account1'])[1]/preceding::h5[1]</value>
      <webElementGuid>75ec9686-9bc7-46ce-8ff0-7f20b7a61102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account2'])[2]/preceding::h5[1]</value>
      <webElementGuid>1d6fcb1a-35e1-435a-9019-bd17c8dfc18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>8a50e9e0-3992-4aae-baf6-8052f44c6a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'testgroup2' or . = 'testgroup2')]</value>
      <webElementGuid>c469d0bb-1db4-40c6-a666-bf92f4ba60df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
