<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_MuiInputBase-input css-mnn31</name>
   <tag></tag>
   <elementGuidId>2e22bd98-891a-4e5c-8aeb-2cd752f0402a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiInputBase-colorPrimary.Mui-focused.css-1imyiyk > input.MuiInputBase-input.css-mnn31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a89aaef4-2db0-4939-a493-4b8ac0e30560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invitation link</value>
      <webElementGuid>a9b8b2fb-468c-4d49-9181-48e910c3bf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42ab8cf4-f1ab-47c0-a470-7e55a27e58a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Invitation link</value>
      <webElementGuid>52c9f1f0-15c3-4649-943c-c0cbd545250d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input css-mnn31</value>
      <webElementGuid>5667c069-a457-4fa8-a35d-9471d018bdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-uhb5lp&quot;]/div[@class=&quot;MuiDialogContent-root css-1ty026z&quot;]/form[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 css-a25rct&quot;]/div[@class=&quot;MuiInputBase-root MuiInputBase-colorPrimary Mui-focused css-1imyiyk&quot;]/input[@class=&quot;MuiInputBase-input css-mnn31&quot;]</value>
      <webElementGuid>708d4099-c697-4867-a99b-3a3f0240f166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>13d0914e-2456-414a-956e-cb1070381504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/input</value>
      <webElementGuid>53415da2-bafe-4a20-9f3e-de6b0950941b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Invitation link' and @type = 'text']</value>
      <webElementGuid>ceaf806f-ad61-43f3-8ac3-8321a2ef2431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
