<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invite friends totestgroup2_MuiInputB_d81c60</name>
   <tag></tag>
   <elementGuidId>50eb2c68-da32-48f4-9134-0824f1885c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[3]/div/div[1]/form[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.MuiInputBase-input.Mui-disabled.css-1k1atk2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21e2c464-1810-4b33-b01c-3ce240bba083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>758980b2-dbbd-4b12-9afc-e0a9b732cc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input Mui-disabled css-1k1atk2</value>
      <webElementGuid>0775c678-c82b-49c4-954d-f23adf2ee226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>http://188.166.184.241/joingroup/0cV75nbZ</value>
      <webElementGuid>8119da62-2483-4577-8034-97315d91b7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-uhb5lp&quot;]/div[@class=&quot;MuiDialogContent-root css-1ty026z&quot;]/form[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 css-1qq160v&quot;]/div[@class=&quot;MuiInputBase-root MuiInputBase-colorPrimary Mui-disabled css-1imyiyk&quot;]/input[@class=&quot;MuiInputBase-input Mui-disabled css-1k1atk2&quot;]</value>
      <webElementGuid>33b4e5d6-32e6-4149-8e07-989c4f057fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='http://188.166.184.241/joingroup/0cV75nbZ']</value>
      <webElementGuid>186aa451-50a9-4c6d-b5e6-f52bdc9fee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6ee14b2c-32ac-454d-ae79-6efd2d130c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>b4dfa843-eeca-43a7-a543-d3e04b5d3bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
